### ISSUE TITLE
Inconsistent default port values

### ISSUE THREAD

**Issue by thegrumble** [michealharker/saraswati-bungee#1]
I noticed there are inconsistent values for the default port.
[config.yml](https://github.com/michealharker/saraswati-bungee/blob/master/src/main/resources/config.yml#L15) default port is 6667
[IRCBot.java](https://github.com/michealharker/saraswati-bungee/blob/master/src/main/java/com/michealharker/saraswati/bungee/IRCBot.java#L34) default port is 6697

**Comment by melamity** [comment]
I've fixed the inconsistent ports so they both read `6667` now, until SSL support is added. (Fixed in 0c01851)
